spring:
  application:
    name: zuul-server
server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}

zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    items:
      service-id: servicio-item
      path: /api/items/**
    usuarios:
      service-id: servicio-usuarios
      path: /api/usuarios/**

#Para modificar el timeout de Hystrix y Ribbon, Hystrix envuelve a Ribbon, por lo que el timeout debe ser mayor.
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
#ribbon:
  #ConnectTimeout: 3000
  #ReadTimeout: 10000