spring:
  application:
    name: zuul-server
  sleuth:
    sampler:
      probability: 1.0 #Probabilidad en la que va a enviar las trazas, solamente en el 10% de las request va a exportar la traza a Zipkin y la idea es que la envie siempre, por eso le cambiamos el valor de 0.1 (10%) que es el por defecto a 1.0 (100%)
    base-url: http://localhost:9411 #Ruta del servidor Zipkin, esto es opcional, por defecto lo busca en local y en el puerto 9411

server:
  port: 8084

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}

zuul:
  routes:
    productos:
      service-id: servicio-productos
      path: /api/productos/**
    items:
      service-id: servicio-item
      path: /api/items/**
    usuarios:
      service-id: servicio-usuarios
      path: /api/usuarios/**
    security:
      service-id: oauth-server
      path: /api/security/**
      sensitive-headers: Cookie, Set-Cookie

#Para modificar el timeout de Hystrix y Ribbon, Hystrix envuelve a Ribbon, por lo que el timeout debe ser mayor.
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 20000
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 10000
